export enum Icons{
    RAIN = 'Rain',
    LIGHT_RAIN = 'Light Rain',
    MIST = 'Mist',
    FOG = 'Fog',
    MAINLY_SUNNY = 'Mainly Sunny',
    PARTYL_CLOUDY = 'Partly Cloudy',
    MOSTLY_CLOUDY = 'Mostly Cloudy',
    CLOUDY = 'Cloudy',
    SUNNY = 'Sunny',
    CLEAR = 'Clear',
    LIGHT_SNOW = 'Light Snow',
    LIGHT_DRIZZLE = 'Light Drizzle',
    MAINLY_CLEAR= 'Mainly Clear',
    LIGHT_RAIN_AND_FOG = 'Light Rain and Fog',
    LIGHT_RAINSHOWER = 'Light Rainshower',
    HAZE = 'Haze',
    FOG_PATCHES = 'Fog Patches',
    THUNDERSTORM_WITH_LIGHT_RAINSHOWERS = 'Thunderstorm with light rainshowers',
    LIGHT_SNOWSHOWER = 'Light Snowshower',
    SNOW    = 'Snow',
    NA = 'Not observed',


    // mostly forecasts
    CHANCE_OF_SHOWERS = 'Chance of showers',
    A_MIX_OF_SUN_AND_CLOUD = 'A mix of sun and cloud',
    PERIODS_OF_RAIN = 'Periods of rain',
    SHOWERS = 'Showers',
    A_FEW_CLOUDS = 'A few clouds',
    CLOUDY_PERIODS = 'Cloudy periods',
    RAIN_OR_DRIZZLE = 'Rain or drizzle',
    RAIN_AT_TIMES_HEAVY_OR_DRIZZLE = 'Rain at times heavy or drizzle',
    RAIN_AT_TIMES_HEAVY = 'Rain at times heavy',
    A_FEW_SHOWERS_OR_DRIZZLE = 'A few showers or drizzle',
    SHOWERS_OR_DRIZZLE = 'Showers or drizzle',
    A_FEW_SHOWERS = 'A few showers',
    CLEARING = 'Clearing',
    FOG_DISSIPATING = 'Fog dissipating',
    INCREASING_CLOUDINESS = 'Increasing cloudiness',
    CHANCE_OF_RAIN_SHOWERS_OR_FLURRIES = 'Chance of rain showers or flurries',
    CHANCE_OF_FLURRIES = 'Chance of flurries',
    SNOW_OR_RAIN = 'Snow or rain',
    RAIN_OR_SNOW = 'Rain or snow',
    CHANCE_OF_FLURRIES_OR_RAIN_SHOWERS = 'Chance of flurries or rain showers',
    FLURRIES_OR_RAIN_SHOWERS = 'Flurries or rain showers',
    PERIODS_OF_RAIN_MIXED_WITH_SNOW = 'Periods of rain mixed with snow',
    A_FEW_FLURRIES = 'A few flurries',
    PERIODS_OF_SNOW = 'Periods of snow',
    PERIODS_OF_RAIN_OR_DRIZZLE = 'Periods of rain or drizzle',
    CHANCE_OF_DRIZZLE_OR_RAIN = 'Chance of drizzle or rain',
    OVERCAST = 'Overcast'

}
